### ISSUE TITLE
TF Website Redesign v1 Checklist

### ISSUE THREAD

**Issue by xenZero999** [Xenyfye/tfweb#1]
### Planned

- [ ] About TF page
- [ ] TF History page (could be on About TF page)
- [ ] Gamemodes & descriptions page

### Possibly

- [ ] Custom Vote page
- [ ] Add status page for all servers within the network
- [ ] Custom Rules page
- [ ] Executive List (seperate page or on index)
- [ ] Staff List (admins and senior admins)
- [ ] Masterbuilder List

### Bugs
- [x] Full button for nav links not clickable (@FolfyBlue)

### Completed
- [x] Tooltip for click to copy (@FolfyBlue)
- [x] Move away from Materialize (@FolfyBlue)
- [x] Add better logo
- [x] Click to copy server IP
- [x] Add favicon
- [x] Make page more responsive
- [x] Show server status & player count

**Comment by JoshuaVandaele** [comment]
PR #3 removes Materialize dependency entirely
